---
swagger: "2.0"
info:
  x-ibm-name: "authservice"
  title: "Authorization Service for Demo"
  version: "1.0.0"
  description: "Sample \n3 parameters : username, password and authorization \nReturn\
    \ 200 if -> \"basic \" + base64(username:password) = authorization sent in the\
    \ request"
schemes:
- "https"
host: "$(catalog.host)"
basePath: "/auth"
securityDefinitions:
  clientIdHeader:
    type: "apiKey"
    description: ""
    in: "header"
    name: "X-IBM-Client-Id"
security:
- {}
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  assembly:
    execute:
    - operation-switch:
        title: "operation-switch"
        case:
        - operations:
          - verb: "get"
            path: "/basic-auth/{username}/{password}"
          execute:
          - gatewayscript:
              title: "gatewayscript"
              version: "1.0.0"
              source: "var reqauth = apim.getvariable('request.authorization').split('\
                \ ');\nvar splitval = new Buffer((reqauth[1] || ''), 'base64').toString('utf8').split(':');\n\
                var username = splitval[0] || '';\nvar password = splitval[1] || '';\n\
                \nif (username === apim.getvariable('request.parameters.username')\
                \ && password === apim.getvariable('request.parameters.password'))\
                \ {\n\tsession.output.write({ \"authenticatedUser\": username });\n\
                \tapim.setvariable('message.headers.api-authenticated-credential',\
                \ 'cn=' + username + ',email=' + username + '@poon.com');\n\tapim.setvariable('message.status.code',\
                \ 200);\n\tapim.output('application/json');\n}\nelse {\n\tapim.setvariable('message.status.code',\
                \ 401);\n}"
        - operations:
          - verb: "get"
            path: "/ping"
          execute:
          - gatewayscript:
              title: "gatewayscript"
              version: "1.0.0"
              source: "session.output.write({\"message\":\"hello world!\"});\napim.output(\"\
                application/json\");"
        otherwise: []
        version: "1.0.0"
    catch: []
  gateway: "datapower-gateway"
  phase: "realized"
paths:
  /ping:
    get:
      responses:
        200:
          description: "200 OK"
  /basic-auth/{username}/{password}:
    get:
      responses:
        200:
          description: "200 OK"
    parameters:
    - $ref: "#/parameters/username"
    - $ref: "#/parameters/password"
    - $ref: "#/parameters/Authorization"
definitions: {}
tags: []
parameters:
  username:
    name: "username"
    type: "string"
    required: true
    in: "path"
  password:
    name: "password"
    type: "string"
    required: true
    in: "path"
  Authorization:
    name: "Authorization"
    type: "string"
    required: false
    in: "header"
